# This is a basic workflow to help you get started with Actions

name: Continuous Integration
env:
  CI: false
# Controls when the action will run.
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Use Node v12 â˜‹
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install packages
        run: npm install
      - name: Build ğŸ”§
        run: npm run build
  
